POST /heroes 
Host: localhost:3333
Content-Type: application/json

{
    "name": "X-Men",
    "category_id":"d7f0cb02-3f12-4cee-9a3c-0e49bfb1f4bc"
}
###
GET  /heroes
Host: localhost:3333
Content-Type: application/json
